# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='headInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=50)),
                ('lianjie', models.CharField(max_length=50)),
                ('artice', models.CharField(max_length=50)),
            ],
        ),
    ]
