# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
