# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20180525_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
